### ISSUE TITLE
Class constructor Link cannot be invoked without 'new'

### ISSUE THREAD

**Issue by ardeaf** [scaleapi/data-prefetch-link#12]
I'm unsure where this error is coming from. Not even sure where it came from. 

```
Class constructor Link cannot be invoked without 'new'
TypeError: Class constructor Link cannot be invoked without 'new'
    at new DataPrefetchLink (/home/ardeaf/projects/blog/node_modules/data-prefetch-link/dist/link.js:54:79)
    at processChild (/home/ardeaf/projects/blog/node_modules/react-dom/cjs/react-dom-server.node.development.js:3182:14)
    at resolve (/home/ardeaf/projects/blog/node_modules/react-dom/cjs/react-dom-server.node.development.js:3147:5)
    at ReactDOMServerRenderer.render (/home/ardeaf/projects/blog/node_modules/react-dom/cjs/react-dom-server.node.development.js:3631:22)
    at ReactDOMServerRenderer.read (/home/ardeaf/projects/blog/node_modules/react-dom/cjs/react-dom-server.node.development.js:3565:29)
    at renderToString (/home/ardeaf/projects/blog/node_modules/react-dom/cjs/react-dom-server.node.development.js:4296:27)
    at render (/home/ardeaf/projects/blog/node_modules/next/dist/next-server/server/render.js:81:16)
    at renderPage (/home/ardeaf/projects/blog/node_modules/next/dist/next-server/server/render.js:283:20)
    at ctx.renderPage (/home/ardeaf/projects/blog/.next/server/static/development/pages/_document.js:1711:26)
    at /home/ardeaf/projects/blog/.next/server/static/development/pages/_document.js:837:17
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/home/ardeaf/projects/blog/.next/server/static/development/pages/_document.js:286:24)
    at _next (/home/ardeaf/projects/blog/.next/server/static/development/pages/_document.js:308:9)
    at /home/ardeaf/projects/blog/.next/server/static/development/pages/_document.js:315:7
    at new Promise (<anonymous>)
    at new F (/home/ardeaf/projects/blog/node_modules/core-js/library/modules/_export.js:36:28)
```

**Comment by kush-agra** [comment]
How did you eventually make it work?

**Comment by ardeaf** [comment]
No, I ended up just using `next export` to run all the `getInitialProps` on all my pages.

`next` is coming out with some utilities soon that will make this easier, namely a new HOC that will run queries you want it to run at build time. As for prefetching, `next export` covered my needs so I didn't pursue further.

Navigating to a route client side still calls `getinitialprops` but soon `getstaticprops` will fix that.

**Comment by kush-agra** [comment]
Ah! sweet, thank you
